# Generated by Django 2.2.2 on 2020-06-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceroom',
            name='organizer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
