# Generated by Django 2.2.2 on 2020-06-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0002_auto_20200605_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceroom',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='starttime',
            field=models.TimeField(null=True),
        ),
    ]
